#!/bin/bash
#
# sim.sh rel. 1.0.0
#

COUNT=320 ## with current parameters, it is about the number of rotations we can daily handle; that's 180k movement per year! 3/4 of Zaventem.
PIDFILE=outr.pid
WORKFILE=outr.csv
TEMPDIR=tmp

TODAY=`date "+%j"`
TOMORROW=$(( $TODAY + 1 ))
YESTERDAY=$(( $TODAY - 1 ))

OLDFILE=outr${YESTERDAY}.csv
TFILE=outr${TODAY}.csv
OFILE=outr${TOMORROW}.csv

if [ ! -d "${TEMPDIR}" ]; then
  mkdir ${TEMPDIR}
fi

temprefix=${TEMPDIR}"/TRANSPORT-"
tempfile=${TEMPDIR}"/TRANSPORTBOARD-"$$.csv

## Erase yesterday
rm -f $OLDFILE

## Generates tomorrow
if [ $COUNT -gt 0 ]
then 
    node mktb.js  -1 -w handler3 -c $COUNT -o $tempfile
    node transboard.js -f $tempfile -p -t ${temprefix} -d
    cat ${temprefix}*.csv | sort -t , -k 3 -o $OFILE
    rm -f ${temprefix}*.{csv,json} ${tempfile}
    rmdir ${TEMPDIR}
fi

## Merge today and tomorrow
cat $TFILE $OFILE | grep -v -i metar | sort -t , -k 3 -o $WORKFILE

## restart post to read new out.csv file
if [ -f $PIDFILE ]
then
    kill `cat $PIDFILE`
fi
node post -p $PIDFILE -t kafka -f $WORKFILE -n now