#!/bin/bash
#
# sim.sh rel. 1.0.0
#

COUNT=0
CLEAN="YES"
POSITIONAL=()

OFILE=out.csv

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -c|--count)
        COUNT="$2"
        shift # past argument
        shift # past value
        ;;
        --clean)
        CLEAN="YES"
        shift # past argument
        ;;
        --dirty)
        CLEAN="NO"
        shift # past argument
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

TEMPDIR=tmp
if [ ! -d "${TEMPDIR}" ]; then
  mkdir ${TEMPDIR}
fi

temprefix=${TEMPDIR}"/FLIGHT-"
tempfile=${TEMPDIR}"/FLIGHTBOARD-"$$.csv

if [ $COUNT -gt 0 ]
then 
    node metar -d
    node mkfb.js -c $COUNT -1 -o ${tempfile}
    node flightboard.js -f $tempfile -p -d -t ${temprefix}
    cat ${temprefix}*.csv | sort -t , -k 3 -o $OFILE
    ls -l $OFILE
    wc -l $OFILE
    cat $tempfile
    head -1 $OFILE
    tail -1 $OFILE
    awk -F , '{print $2}' $OFILE |grep fuel |sort -u
    awk -F , '{print $2}' $OFILE |grep catering |sort -u
    awk -F , '{print $2}' $OFILE |grep sewage |sort -u
    awk -F , '{print $2}' $OFILE |grep cargo |sort -u
fi

if [ $CLEAN = "YES" ]
then
    mv $tempfile ./out_.csv
    rm -f ${temprefix}*.{csv,json}
    rmdir ${TEMPDIR}
fi
